//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya18
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заключение договора.
    /// </summary>
    // *** Start programmer edit section *** (ЗаключДоговора CustomAttributes)

    // *** End programmer edit section *** (ЗаключДоговора CustomAttributes)
    [AutoAltered()]
    [Caption("Заключение договора")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаключДоговораE", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность",
            "Стоимость as \'Стоимость\'",
            "ДирОтдПоРабСКл",
            "ДирОтдПоРабСКл.Фамилия",
            "Клиент",
            "Клиент.Фамилия"})]
    [View("ЗаключДоговораL", new string[] {
            "Дата as \'Дата\'",
            "Номер as \'Номер\'",
            "Тип as \'Тип\'",
            "Длительность",
            "Стоимость as \'Стоимость\'",
            "ДирОтдПоРабСКл",
            "ДирОтдПоРабСКл.Фамилия",
            "Клиент",
            "Клиент.Фамилия"})]
    public class ЗаключДоговора : ICSSoft.STORMNET.DataObject
    {
        
        private int fСтоимость;
        
        private System.DateTime fДата;
        
        private int fНомер;
        
        private IIS.Kursovaya18.ТипДоговора fТип;
        
        private int fДлительность;
        
        private IIS.Kursovaya18.ДирОтдПоРабСКл fДирОтдПоРабСКл;
        
        private IIS.Kursovaya18.Клиент fКлиент;
        
        // *** Start programmer edit section *** (ЗаключДоговора CustomMembers)

        // *** End programmer edit section *** (ЗаключДоговора CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Дата Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаключДоговора.Дата Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Дата Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Дата Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Дата Set end)
            }
        }
        
        /// <summary>
        /// Длительность.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Длительность CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Длительность CustomAttributes)
        public virtual int Длительность
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Длительность Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Длительность Get start)
                int result = this.fДлительность;
                // *** Start programmer edit section *** (ЗаключДоговора.Длительность Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Длительность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Длительность Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Длительность Set start)
                this.fДлительность = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Длительность Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Длительность Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Номер Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаключДоговора.Номер Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Номер Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Номер Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Номер Set end)
            }
        }
        
        /// <summary>
        /// Стоимость.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Стоимость CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Стоимость CustomAttributes)
        public virtual int Стоимость
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Стоимость Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Стоимость Get start)
                int result = this.fСтоимость;
                // *** Start programmer edit section *** (ЗаключДоговора.Стоимость Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Стоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Стоимость Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Стоимость Set start)
                this.fСтоимость = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Стоимость Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Стоимость Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Тип CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Тип CustomAttributes)
        public virtual IIS.Kursovaya18.ТипДоговора Тип
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Тип Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Тип Get start)
                IIS.Kursovaya18.ТипДоговора result = this.fТип;
                // *** Start programmer edit section *** (ЗаключДоговора.Тип Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Тип Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Тип Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Тип Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл CustomAttributes)
        [PropertyStorage(new string[] {
                "ДирОтдПоРабСКл"})]
        [NotNull()]
        public virtual IIS.Kursovaya18.ДирОтдПоРабСКл ДирОтдПоРабСКл
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Get start)

                // *** End programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Get start)
                IIS.Kursovaya18.ДирОтдПоРабСКл result = this.fДирОтдПоРабСКл;
                // *** Start programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Get end)

                // *** End programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Set start)

                // *** End programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Set start)
                this.fДирОтдПоРабСКл = value;
                // *** Start programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Set end)

                // *** End programmer edit section *** (ЗаключДоговора.ДирОтдПоРабСКл Set end)
            }
        }
        
        /// <summary>
        /// Заключение договора.
        /// </summary>
        // *** Start programmer edit section *** (ЗаключДоговора.Клиент CustomAttributes)

        // *** End programmer edit section *** (ЗаключДоговора.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya18.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Клиент Get start)

                // *** End programmer edit section *** (ЗаключДоговора.Клиент Get start)
                IIS.Kursovaya18.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ЗаключДоговора.Клиент Get end)

                // *** End programmer edit section *** (ЗаключДоговора.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаключДоговора.Клиент Set start)

                // *** End programmer edit section *** (ЗаключДоговора.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ЗаключДоговора.Клиент Set end)

                // *** End programmer edit section *** (ЗаключДоговора.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаключДоговораE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключДоговораE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключДоговораE", typeof(IIS.Kursovaya18.ЗаключДоговора));
                }
            }
            
            /// <summary>
            /// "ЗаключДоговораL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаключДоговораL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаключДоговораL", typeof(IIS.Kursovaya18.ЗаключДоговора));
                }
            }
        }
    }
}
